######################################################################
##
## Filename: coin_rx.udo
## Created on: Thu Oct 29 10:10:37 AM Eastern Daylight Time 2015
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
