######################################################################
##
## Filename: Coin_controller.udo
## Created on: Thu Oct 22 11:46:41 AM Eastern Daylight Time 2015
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
