######################################################################
##
## Filename: Usr_interaction.udo
## Created on: Thu Oct 29 8:55:31 AM Eastern Daylight Time 2015
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
